### ISSUE TITLE
There is error in your example?

### ISSUE THREAD

**Issue by subasah** [aseba/php-instagram#1]
When i ran you example mentioned, i came out with the error like : stdClass Object ( [pagination] => stdClass Object ( [deprecation_warning] => next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead ) [meta] => stdClass Object ( [code] => 200 ) [data] => Array ( ) )

after 
var_dump($content); 

I am in sandbox mode right now.

**Comment by subasah** [comment]
$content = $instagram->generic('/tags/love/media/recent');


Returns no data, Could you help me? Despite being in the live mode

**Comment by subasah** [comment]
Thanks bro, Finally it worked!!  The main problem was that i did not add the credential like client id and client secret

**Comment by aseba** [comment]
I'm glad you figured out on your own!
